In [ ]:
3+4


7

In [ ]:
3+10

13

In [ ]:
city_name = "PUNJAB"
print(f"City Name: {city_name}")

City Name: PUNJAB


In [ ]:
celsius = 25
fahr=(celsius * 1.8) + 32
print(f"Temperature: {celsius} degree Celsius")
print(f"Temperature: {fahr} degree fahrenheit")

Temperature: 25 degree Celsius
Temperature: 77.0 degree fahrenheit


In [ ]:
carbon=float(input("enter the carbon footprint"))
print(f"carbon footprint : {carbon} kg CO2.")
is_sustainable = carbon < 400
print(f"good boy")

In [ ]:
num=input("enter a number: ")
ans=num.isdigit()
print(ans)

enter a number: money
False


In [ ]:
a=[1,5,4,6,8]
b=5
if b in a:
  print("hi shaurya")
else :
  print("hi himanshu")

hi shaurya


In [ ]:
num1=int(input("enter first number :"))
num2=int(input("enter second number :"))
operator=input("enter operator (+,-,*,/,%)")
if(operator=='+'):
  print(num1+num2)
elif(operator=='-'):
  print(num1-num2)
elif(operator=='*'):
  print(num1*num2)
elif(operator=='/'):
  print(num1/num2)
elif(operator=='%'):
  print(num1%num2)
else:
  print('wrong operator please')


enter first number :5
enter second number :09
enter operator (+,-,*,/,%)*
45


In [ ]:
high_temp_threshold = 26
high_temp_cities=[city for city in climate_data if city["temperature"] > high_temp_threshold]
print("cities with high temperatures (>26 C):")
for city in high_temp_cities:
  print(f"{city['city']}-{city['temperature']}C")


NameError: name 'climate_data' is not defined

In [ ]:
highest_footprint_city = max(climate_data,key+lambda city: city["carbon_footprint"])
print(f"\nCity with the highest carbon footprint:")
print(f"{highest_footprint_city['city']-{highest_footprint_city['carbon_footprint']}}")

In [ ]:
energy = 1000
emission = 0.475

carbon_footprint = calculate_carbon_footprint(energy,emission)
print(f"carbon footprint: {carbon_footprint} kg CO2")


NameError: name 'calculate_carbon_footprint' is not defined

In [ ]:
leapy = lambda year: (year % 4 ==0 and year % 100 != 0) or (year % 400 ==0)

year = int(input("Enter a year : "))
print(f"{year} is a leap year : {leapy(year)}")

Enter a year : 1998
1998 is a leap year : False


In [ ]:
import pandas as pd
renewable_sources = ["Solar","Wind","Hydropower","Geothermal","Biomass"]
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150,300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022,2025,2023]
}
renewable_series = pd.Series(renewable_sources)
print("renewable energy resources :")
#print(renewable_series)
projects_df = pd.DataFrame(data)
#projects_df.head()
#projects_df.tail()
#selected=projects_df.iloc[[1,2]]
#print(selected)
#projects_df.info()
#projects_df.describe()


renewable energy resources :


In [ ]:
import pandas as pd

# Create DataFrame
projects_df = pd.DataFrame(data)

# Filter projects with capacity > 100 MW
high_capacity_projects = projects_df[projects_df['Capacity (MW)'] > 100]

# Display the result
print(high_capacity_projects)



NameError: name 'data' is not defined

In [ ]:
import pandas as pd

# Create DataFrame
projects_df = pd.DataFrame(data)

# Add a new column for cost per megawatt
projects_df['Cost per MW ($)'] = projects_df['Cost (Million $)'] / projects_df['Capacity (MW)']

# Display the updated DataFrame
print(projects_df)


#tot_capacity = projects_df["capacity"]



NameError: name 'data' is not defined

In [ ]:
import pandas as pd
renewable_sources = ["Solar","Wind","Hydropower","Geothermal","Biomass"]
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150,300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022,2025,2023]
}
renewable_series = pd.Series(renewable_sources)
projects_df = pd.DataFrame(data)

grouped_data = projects_df.groupby("Technology")["Capacity (MW)"].sum()
print("\nTotal Capacity by Technology")
print(grouped_data)


Total Capacity by Technology
Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


In [ ]:
import numpy as np
one_d_array = np.array([1,2,3])
print(one_d_array)

[1 2 3]


In [ ]:
two_d_array = np.array([[1,2,3],[3,4,5]])
#print(two_d_array)
#two_d_array.shape
#two_d_array.ndim
#two_d_array.dtype
#two_d_array.size
#two_d_array.itemsize
reshape1=two_d_array.reshape(2,3)
print(reshape1)

[[1 2 3]
 [3 4 5]]


In [ ]:
np.ones(3)
np.zeros(6)
np.random.random(3)


array([0.3433625 , 0.29780572, 0.33063346])

In [ ]:
array = np.full((3,3),10)
print(array)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
identity_array = np.identity(6)
print(identity_array)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
array1 = np.arange(10)
#print(array1)
reshape1=array1.reshape(2,5)
print(reshape1)
transpose=reshape1.T
print(transpose)
print(transpose.flatten('F'))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
array1 = np.arange(0,10,2)
print(array1)

[0 2 4 6 8]


In [ ]:
linspace=np.linspace(5,10,3,endpoint="TRUE" )
print(linspace)

[ 5.   7.5 10. ]


In [ ]:
linspace=np.linspace(0,100,10, retstep="TRUE")
print(linspace)

(array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ]), 11.11111111111111)


In [ ]:
num_data = np.array([11,22,33,44,55,66,77,88,99])
#print(num_data[:])
#print(num_data[::1])
#print(num_data[::2])
#print(num_data[::-1])
num1 =num_data[:]
num2 =num_data[:-1]
if(num1==num2):
  print("string is palindrome.")
else:
  print("string is not a palindrome.")

ValueError: operands could not be broadcast together with shapes (9,) (8,) 

In [ ]:
import numpy as np
energy_consumption = np.array([1200,3400,2900,1800,2500])
reshaped_energy=energy_consumption.reshape(5,1)
print(energy_consumption)
print("Energy Consumption (in MWh) for Different Renewable Sources: ")
print(energy_consumption)

# Calculate the mean
mean_consumption = np.mean(energy_consumption)
print("Mean energy consumption (kWh):", mean_consumption)

# Calculate the median
median_consumption = np.median(energy_consumption)
print("Median energy consumption (kWh):", median_consumption)

# Calculate the standard deviation
std_dev_consumption = np.std(energy_consumption)
print("Standard deviation of energy consumption (kWh):", std_dev_consumption)

# Calculate the variance
variance_consumption = np.var(energy_consumption)
print("Variance of energy consumption (kWh):", variance_consumption)

[1200 3400 2900 1800 2500]
Energy Consumption (in MWh) for Different Renewable Sources: 
[1200 3400 2900 1800 2500]
Mean energy consumption (kWh): 2360.0
Median energy consumption (kWh): 2500.0
Standard deviation of energy consumption (kWh): 781.2809993849844
Variance of energy consumption (kWh): 610400.0
